baseURL = "/"
title = "C Kalansuriya & Sons"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "C Kalansuriya & Sons" # title for frontpage, may include image
copyright = "C Kalansuriya and sons"
description = 'Authorized Distributor for Munchee CBL, Prima Ceylon, Prima Grain Elevators Down South'
startbuttonText = "Activate"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'We are a diversified business which specializes in Distribution, Hospitality, Agriculture, Power etc.'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/prima_flour_products.jpg"
title = 'Prima Flour Wholesale & Retail Distributor - Galle'
body = 'C. Kalansuriya & Sons holds the authorized distributorship for Prima Quality wheat flour in Galle, serving both individual consumers through our retail location on Dangedara Street, Galle City, and fulfilling the bulk requirements of bakeries and shops across the wider Galle area through our dedicated distribution network.'

[[params.two.section]]
img = "img/mega_stores_two.jpg"
title = 'Mega Stores - Prima Ceylon'
body = 'As a key partner of Prima Ceylon, we manage one of their select mega stores nationwide, serving as the central distribution point for wheat flour to all distributors throughout the Southern region.'

[[params.two.section]]
img = "img/estate.JPG"
img_alt = "blurry background: white/grey"
title = 'Tea plantation'
body = 'For more than three decades and a half, our passion for the art of tea cultivation has been the cornerstone of our successful and thriving tea estate in the low country, building a rich heritage of quality tea production and sustainable practices rooted in care.'

[[params.two.section]]
img = "img/hotel4.jpg"
title = 'Hospitality: <br />Gloria Grand Hotel Unawatuna'
body = 'For a decade, we have successfully operated one of the consistently top-rated hotels in the prime area of Unawatuna, demonstrating resilience and adaptability through significant industry challenges such as the COVID-19 pandemic.'

[[params.two.section]]
img = "img/station.jpg"
title = 'Fuel Distribution - IOC'
body = 'As a long-standing business partner with IOC in the petroleum retail industry, our company brings over a decade of operational experience, successfully navigating industry complexities and ensuring the sustained management of our fuel station which is located in a prime location in Galle.'

[params.three]
enable = true
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Based in Galle District"
body = "Established over four decades ago in Galle, C. Kalansuriya & Sons represents a legacy family business that has strategically diversified its interests across multiple sectors. While demonstrating adaptability and growth across various industries, our core strength and enduring expertise lie within the robust field of distribution."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "If you are looking for a distributor for your product in Galle leave us a message"
phone = "+94 777907440"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "contact@ckalanandsons.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
